In [22]:
import numpy as np
import pandas as pd


# In[2]:

In [25]:
data = pd.read_csv('KESTREL.csv')

In [26]:
data.head()

,Time,Temp,Wet Bulb Temp.,Rel. Hum.,Baro.,Altitude,Station P.,Wind Speed,Heat Index,Dew Point,Dens. Alt.,Crosswind,Headwind,Mag. Dir.,True Dir.,Wind Chill
0,2019-05-23 19:10:40,26.9,20.4,56.0,999.7,110,999.7,0.0,27.5,17.4,638,***,***,***,***,26.9
1,2019-05-23 19:10:45,26.9,20.4,56.0,998.9,118,998.9,0.0,27.5,17.4,645,***,***,***,***,26.9
2,2019-05-23 19:10:50,26.8,20.4,56.1,999.0,118,999.0,0.0,27.2,17.3,638,***,***,***,***,26.7
3,2019-05-23 19:10:55,26.6,20.2,56.2,998.9,118,998.9,0.0,27.1,17.2,633,***,***,***,***,26.6
4,2019-05-23 19:11:00,26.5,20.2,56.4,999.0,117,999.0,0.0,26.9,17.1,628,***,***,***,***,26.5

In [28]:
# In[5]:


times = pd.DatetimeIndex(data.Time)
grouped = data.groupby([times.day, times.hour, times.minute]).mean()


# In[6]:


grouped = pd.DataFrame(grouped)


# In[7]:


grouped.to_csv('KESTREL_avg')